<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{de26eae3-e59b-44be-b1f6-bb2eefb06bbb}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	ledState : BOOL;
	ledMultiState : INT;	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>